-- Bảng User
INSERT INTO user (user_id, username, password, email, avatar, create_date, count_sign_in, active, subscription) VALUES

                                                                                                                    (1,'user1', '', 'user1@example.com', 'avatar1.jpg', '2023-10-27 10:00:00', 0, true, '2024-10-27 10:00:00'),
                                                                                                                    (2,'user2', '12345678', 'user2@example.com', 'avatar2.jpg', '2023-10-28 12:30:00', 0, true, NULL),
                                                                                                                    (3,'user3', '12345678', 'user3@example.com', 'avatar3.jpg', '2023-10-29 15:45:00', 0, false, '2023-11-29 15:45:00'),
                                                                                                                    (4,'user4', '12345678', 'user4@example.com', 'avatar4.jpg', '2023-10-30 18:00:00', 0, true, '2024-10-30 18:00:00'),
                                                                                                                    (5,'user5', '12345678', 'user5@example.com', 'avatar5.jpg', '2023-10-31 20:30:00', 0, false, NULL),
                                                                                                                    (6,'user6', '12345678', 'user6@example.com', 'avatar6.jpg', '2023-11-01 22:45:00', 0, true, '2024-11-01 22:45:00'),
                                                                                                                    (7,'user7', '12345678', 'user7@example.com', 'avatar7.jpg', '2023-11-02 10:00:00', 0, true, NULL),
                                                                                                                    (8,'user8', '12345678', 'user8@example.com', 'avatar8.jpg', '2023-11-03 12:30:00', 0, false, '2023-12-03 12:30:00'),
                                                                                                                    (9,'user9', '12345678', 'user9@example.com', 'avatar9.jpg', '2023-11-04 15:45:00', 0, true, '2024-11-04 15:45:00'),
                                                                                                                    (10,'user10', '12345678', 'user10@example.com', 'avatar10.jpg', '2023-11-05 18:00:00', 0, true, NULL);

-- Bảng Role
INSERT INTO role (name, description) VALUES
                                         ('USER', 'Người dùng thông thường'),
                                         ('MODERATOR', 'Người kiểm duyệt'),
                                         ('EDITOR', 'Người biên tập'),
                                         ('CONTRIBUTOR', 'Người đóng góp'),
                                         ('AUTHOR', 'Tác giả'),
                                         ('SUBSCRIBER', 'Người đăng ký'),
                                         ('VIP', 'Thành viên VIP'),
                                         ('GUEST', 'Khách'),
                                         ('TESTER', 'Người kiểm thử');

-- Bảng Permission
INSERT INTO permission (name, description) VALUES
                                               ('READ', 'Quyền đọc dữ liệu'),
                                               ('WRITE', 'Quyền ghi dữ liệu'),
                                               ('DELETE', 'Quyền xóa dữ liệu'),
                                               ('CREATE', 'Quyền tạo dữ liệu'),
                                               ('UPDATE', 'Quyền cập nhật dữ liệu'),
                                               ('MANAGE', 'Quyền quản lý'),
                                               ('APPROVE', 'Quyền phê duyệt'),
                                               ('PUBLISH', 'Quyền xuất bản'),
                                               ('COMMENT', 'Quyền bình luận'),
                                               ('RATE', 'Quyền đánh giá');

-- Bảng User_Roles
INSERT INTO user_roles (user_id, role_name) VALUES
                                                ((SELECT user.user_id FROM User WHERE username = 'user1'), 'USER'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user2'), 'ADMIN'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user3'), 'USER'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user4'), 'MODERATOR'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user5'), 'USER'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user6'), 'ADMIN'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user7'), 'USER'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user8'), 'EDITOR'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user9'), 'USER'),
                                                ((SELECT user.user_id FROM User WHERE username = 'user10'), 'ADMIN');

-- Bảng Genre
INSERT INTO genre (genre_name, description) VALUES
                                                ('Pop', 'Nhạc Pop'),
                                                ('Rock', 'Nhạc Rock'),
                                                ('Electronic', 'Nhạc điện tử'),
                                                ('Hip-hop', 'Nhạc Hip-hop'),
                                                ('R&B', 'Nhạc R&B'),
                                                ('Country', 'Nhạc đồng quê'),
                                                ('Jazz', 'Nhạc Jazz'),
                                                ('Classical', 'Nhạc cổ điển'),
                                                ('Blues', 'Nhạc Blues'),
                                                ('Folk', 'Nhạc dân gian');

-- Bảng Artist
INSERT INTO artist (artist_name, avatar) VALUES
                                             ('Taylor Swift', 'taylor.jpg'),
                                             ('Imagine Dragons', 'imaginedragons.jpg'),
                                             ('The Chainsmokers', 'thechainsmokers.jpg'),
                                             ('Ed Sheeran', 'edsheeran.jpg'),
                                             ('Adele', 'adele.jpg'),
                                             ('Maroon 5', 'maroon5.jpg'),
                                             ('Coldplay', 'coldplay.jpg'),
                                             ('Ariana Grande', 'arianagrande.jpg'),
                                             ('Drake', 'drake.jpg'),
                                             ('Justin Bieber', 'justinbieber.jpg');

-- Bảng Album
INSERT INTO album (album_name, description, release_date, image, artist_id) VALUES
                                                                                ('Lover', 'Album Lover của Taylor Swift', '2019-08-23T00:00:00', 'lover.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift')),
                                                                                ('Evolve', 'Album Evolve của Imagine Dragons', '2017-06-23T00:00:00', 'evolve.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons')),
                                                                                ('Sick Boy', 'Album Sick Boy của The Chainsmokers', '2018-01-17T00:00:00', 'sickboy.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers')),
                                                                                ('Divide', 'Album Divide của Ed Sheeran', '2017-03-03T00:00:00', 'divide.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran')),
                                                                                ('25', 'Album 25 của Adele', '2015-11-20T00:00:00', '25.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Adele')),
                                                                                ('Red Pill Blues', 'Album Red Pill Blues của Maroon 5', '2017-11-03T00:00:00', 'redpillblues.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5')),
                                                                                ('A Head Full of Dreams', 'Album A Head Full of Dreams của Coldplay', '2015-12-04T00:00:00', 'aheadfullofdreams.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay')),
                                                                                ('Sweetener', 'Album Sweetener của Ariana Grande', '2018-08-17T00:00:00', 'sweetener.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande')),
                                                                                ('Scorpion', 'Album Scorpion của Drake', '2018-06-29T00:00:00', 'scorpion.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Drake')),
                                                                                ('Purpose', 'Album Purpose của Justin Bieber', '2015-11-13T00:00:00', 'purpose.jpg', (SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'));

-- Bảng Song
INSERT INTO song (song_tittle, release_date, duration, file_path, image, likes, downloads, genre_id) VALUES
                                                                                                         ('Blank Space', 2014, '00:03:51', 'blankspace.mp3', 'blankspace.jpg', 1000, 500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
                                                                                                         ('Believer', 2017, '00:03:24', 'believer.mp3', 'believer.jpg', 1500, 700, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
                                                                                                         ('Closer', 2016, '00:04:04', 'closer.mp3', 'closer.jpg', 2000, 1000, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
                                                                                                         ('Shape of You', 2017, '00:03:53', 'shapeofyou.mp3', 'shapeofyou.jpg', 2500, 1200, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
                                                                                                         ('Hello', 2015, '00:04:55', 'hello.mp3', 'hello.jpg', 3000, 1500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
                                                                                                         ('Girls Like You', 2018, '00:04:05', 'girlslikeyou.mp3', 'girlslikeyou.jpg', 3500, 1700, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
                                                                                                         ('Something Just Like This', 2017, '00:04:07', 'somethingjustlikethis.mp3', 'somethingjustlikethis.jpg', 4000, 2000, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
                                                                                                         ('No Tears Left to Cry', 2018, '00:03:25', 'notearslefttocry.mp3', 'notearslefttocry.jpg', 4500, 2200, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
                                                                                                         ('God s Plan', 2018, '00:03:18', 'godsplan.mp3', 'godsplan.jpg', 5000, 2500, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
                                                                                                         ('Love Yourself', 2015, '00:03:53', 'loveyourself.mp3', 'loveyourself.jpg', 5500, 2700, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop'));


-- Bảng Playlist
INSERT INTO playlist (playlist_name, create_date, user_id) VALUES
                                                               ('Nhạc yêu thích', '2023-10-26 14:00:00', (SELECT user.user_id FROM User WHERE username = 'user1')),
                                                               ('Nhạc thư giãn', '2023-10-27 16:30:00', (SELECT user.user_id FROM User WHERE username = 'user2')),
                                                               ('Nhạc năng động', '2023-10-28 18:45:00', (SELECT user.user_id FROM User WHERE username = 'user3')),
                                                               ('Nhạc buồn', '2023-10-29 20:00:00', (SELECT user.user_id FROM User WHERE username = 'user4')),
                                                               ('Nhạc vui', '2023-10-30 22:30:00', (SELECT user.user_id FROM User WHERE username = 'user5')),
                                                               ('Nhạc học tập', '2023-10-31 00:45:00', (SELECT user.user_id FROM User WHERE username = 'user6')),
                                                               ('Nhạc làm việc', '2023-11-01 02:00:00', (SELECT user.user_id FROM User WHERE username = 'user7')),
                                                               ('Nhạc tập thể dục', '2023-11-02 04:30:00', (SELECT user.user_id FROM User WHERE username = 'user8')),
                                                               ('Nhạc du lịch', '2023-11-03 06:45:00', (SELECT user.user_id FROM User WHERE username = 'user9')),
                                                               ('Nhạc giải stress', '2023-11-04 08:00:00', (SELECT user.user_id FROM User WHERE username = 'user10'));

-- Bảng Playlist_Song
INSERT INTO playlist_song (playlist_id, song_id) VALUES
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc yêu thích'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Blank Space')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc thư giãn'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Believer')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc năng động'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Closer')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc buồn'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Shape of You')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc vui'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Hello')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc học tập'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Girls Like You')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc làm việc'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Something Just Like This')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc tập thể dục'), (SELECT song.song_id FROM Song WHERE song_tittle = 'No Tears Left to Cry')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc du lịch'), (SELECT song.song_id FROM Song WHERE song_tittle = 'God s Plan')),
                                                     ((SELECT playlist_id FROM Playlist WHERE playlist_name = 'Nhạc giải stress'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Love Yourself'));

-- Bảng Comment
INSERT INTO comment (content, create_date, parent_id, rate, user_id, song_id) VALUES
                                                                                  ('Bài hát hay quá!', '2023-10-29 09:00:00', -1, 5, (SELECT user.user_id FROM User WHERE username = 'user1'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Blank Space')),
                                                                                  ('Tôi rất thích bài hát này!', '2023-10-30 11:30:00', -1, 4, (SELECT user.user_id FROM User WHERE username = 'user2'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Believer')),
                                                                                  ('Tuyệt vời!', '2023-10-31 13:45:00', 1, 5, (SELECT user.user_id FROM User WHERE username = 'user3'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Blank Space')),
                                                                                  ('Bài hát này thật ý nghĩa!', '2023-11-01 15:00:00', -1, 3, (SELECT user.user_id FROM User WHERE username = 'user4'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Shape of You')),
                                                                                  ('Giai điệu thật bắt tai!', '2023-11-02 17:30:00', -1, 5, (SELECT user.user_id FROM User WHERE username = 'user5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Hello')),
                                                                                  ('Tôi đã nghe đi nghe lại nhiều lần!', '2023-11-03 19:45:00', -1, 4, (SELECT user.user_id FROM User WHERE username = 'user6'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Girls Like You')),
                                                                                  ('Âm thanh tuyệt vời!', '2023-11-04 21:00:00', 7, 5, (SELECT user.user_id FROM User WHERE username = 'user7'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Something Just Like This')),
                                                                                  ('Ca sĩ hát rất hay!', '2023-11-05 23:30:00', -1, 4, (SELECT user.user_id FROM User WHERE username = 'user8'), (SELECT song.song_id FROM Song WHERE song_tittle = 'No Tears Left to Cry')),
                                                                                  ('Lời bài hát sâu sắc!', '2023-11-06 01:45:00', -1, 3, (SELECT user.user_id FROM User WHERE username = 'user9'), (SELECT song.song_id FROM Song WHERE song_tittle = 'God s Plan')),
                                                                                  ('Một bài hát kinh điển!', '2023-11-07 03:00:00', -1, 5, (SELECT user.user_id FROM User WHERE username = 'user10'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Love Yourself'));


-- Bảng Artist_Song
INSERT INTO artist_song (artist_id, song_id) VALUES
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Blank Space')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Believer')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Closer')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Shape of You')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Hello')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Girls Like You')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Something Just Like This')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'No Tears Left to Cry')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'God s Plan')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Love Yourself'));

-- Bảng Menu
INSERT INTO menu (link, title, order_list) VALUES
                                               ('/home', 'Trang chủ', 1),
                                               ('/songs', 'Bài hát', 2),
                                               ('/playlists', 'Playlist', 3),
                                               ('/artists', 'Nghệ sĩ', 4),
                                               ('/albums', 'Album', 5),
                                               ('/genres', 'Thể loại', 6),
                                               ('/search', 'Tìm kiếm', 7),
                                               ('/upload', 'Tải lên', 8),
                                               ('/profile', 'Hồ sơ', 9),
                                               ('/settings', 'Cài đặt', 10);

-- Bảng InvalidatedToken
INSERT INTO invalidated_token (id, expiry_time) VALUES
                                                    ('oldtoken123', '2023-10-26 10:00:00'),
                                                    ('expiredtoken456', '2023-10-27 12:00:00'),
                                                    ('invalidtoken789', '2023-10-28 14:00:00'),
                                                    ('badtokenabc', '2023-10-29 16:00:00'),
                                                    ('dummytokendef', '2023-10-30 18:00:00'),
                                                    ('testtokenghi', '2023-10-31 20:00:00'),
                                                    ('faketokenjkl', '2023-11-01 22:00:00'),
                                                    ('mocktokenmno', '2023-11-02 00:00:00'),
                                                    ('sampletokenpqr', '2023-11-03 02:00:00'),
                                                    ('randomtokenstu', '2023-11-04 04:00:00');



INSERT INTO song (song_tittle, release_date, duration, file_path, image, likes, downloads, genre_id) VALUES
('Style', 2014, '00:03:50', 'style.mp3', 'style.png', 1100, 550, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Bad Blood', 2015, '00:03:57', 'badblood.mp3', 'badblood.png', 1300, 650, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Wildest Dreams', 2015, '00:03:54', 'wildestdreams.mp3', 'wildestdreams.png', 1050, 525, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Out of the Woods', 2015, '00:03:55', 'outofthewoods.mp3', 'outofthewoods.png', 1150, 575, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Welcome to New York', 2014, '00:03:32', 'welcometonewyork.mp3', 'welcometonewyork.png', 900, 450, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('I Knew You Were Trouble', 2012, '00:03:39', 'iknewyouweretrouble.mp3', 'iknewyouweretrouble.jpg', 1400, 700, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('We Are Never Ever Getting Back Together', 2012, '00:03:13', 'weareneverevergettingbacktogether.mp3', 'weareneverevergettingbacktogether.jpg', 1500, 750, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Red', 2012, '00:03:42', 'red.mp3', 'red.jpg', 1000, 500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Thunder', 2017, '00:03:52', 'thunder.mp3', 'thunder.jpg', 1300, 650, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('It s Time', 2012, '00:04:08', 'itstime.mp3', 'itstime.jpg', 1100, 550, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Radioactive', 2012, '00:03:08', 'radioactive.mp3', 'radioactive.jpg', 1400, 700, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Demons', 2013, '00:03:53', 'demons.mp3', 'demons.jpg', 1200, 600, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('On Top of the World', 2012, '00:03:14', 'ontopoftheworld.mp3', 'ontopoftheworld.jpg', 1000, 500, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Shots', 2017, '00:03:27', 'shots.mp3', 'shots.png', 1150, 575, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Natural', 2018, '00:03:34', 'natural.mp3', 'natural.png', 1350, 675, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Walking the Wire', 2018, '00:03:45', 'walkingthewire.mp3', 'walkingthewire.jpg', 1250, 625, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Zero', 2018, '00:03:58', 'zero.mp3', 'zero.jpg', 1050, 525, (SELECT genre_id FROM Genre WHERE genre_name = 'Rock')),
('Don t Let Me Down', 2016, '00:03:56', 'dontletmedown.mp3', 'dontletmedown.png', 1800, 900, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Paris', 2017, '00:03:48', 'paris.mp3', 'paris.png', 1900, 950, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Roses', 2017, '00:03:59', 'roses.mp3', 'roses.png', 1600, 800, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Everybody Hates Me', 2018, '00:03:42', 'everybodyhatesme.mp3', 'everybodyhatesme.png', 1300, 650, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Who Do You Love', 2018, '00:03:37', 'whodoyoulove.mp3', 'whodoyoulove.png', 1200, 600, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Thinking Out Loud', 2014, '00:04:29', 'thinkingoutloud.mp3', 'thinkingoutloud.png', 2300, 1150, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Perfect', 2017, '00:04:23', 'perfect.mp3', 'perfect.jpg', 2400, 1200, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Photograph', 2014, '00:04:18', 'photograph.mp3', 'photograph.png', 2200, 1100, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Happier', 2017, '00:03:49', 'happier.mp3', 'happier.png', 2100, 1050, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Galway Girl', 2017, '00:03:55', 'galwaygirl.mp3', 'galwaygirl.jpg', 2000, 1000, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Castle on the Hill', 2017, '00:04:10', 'castleonthehill.mp3', 'castleonthehill.png', 1900, 950, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Someone Like You', 2011, '00:04:52', 'someonelikeyou.mp3', 'someonelikeyou.png', 2800, 1400, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Set Fire to the Rain', 2011, '00:04:01', 'setfiretotherain.mp3', 'setfiretotherain.png', 2700, 1350, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Rumour Has It', 2011, '00:03:56', 'rumourhasit.mp3', 'rumourhasit.png', 2600, 1300, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Turning Tables', 2011, '00:03:47', 'turningtables.mp3', 'turningtables.png', 2500, 1250, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Set Fire to the Rain', 2011, '00:04:01', 'setfiretotherain.mp3', 'setfiretotherain.jpg', 2700, 1350, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Rumour Has It', 2011, '00:03:56', 'rumourhasit.mp3', 'rumourhasit.jpg', 2600, 1300, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Turning Tables', 2011, '00:03:47', 'turningtables.mp3', 'turningtables.jpg', 2500, 1250, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Memories', 2019, '00:03:58', 'memories.mp3', 'memories.png', 3300, 1650, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Sugar', 2014, '00:03:55', 'sugar.mp3', 'sugar.png', 3200, 1600, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Payphone', 2012, '00:03:52', 'payphone.mp3', 'payphone.png', 3100, 1550, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Moves Like Jagger', 2011, '00:03:57', 'moveslikejagger.mp3', 'moveslikejagger.png', 3000, 1500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('She Will Be Loved', 2004, '00:03:54', 'shewillbeloved.mp3', 'shewillbeloved.png', 2800, 1400, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Animals', 2014, '00:03:50', 'animals.mp3', 'animals.png', 2700, 1350, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('One More Night', 2012, '00:04:03', 'onemorenight.mp3', 'onemorenight.png', 2600, 1300, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Maps', 2014, '00:03:57', 'maps.mp3', 'maps.png', 2500, 1250, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Hymn for the Weekend', 2016, '00:04:25', 'hymnfortheweekend.mp3', 'hymnfortheweekend.jpg', 3800, 1900, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Adventure of a Lifetime', 2015, '00:04:23', 'adventureofalifetime.mp3', 'adventureofalifetime.jpg', 3700, 1850, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('A Sky Full of Stars', 2014, '00:04:28', 'askyfullofstars.mp3', 'askyfullofstars.png', 3600, 1800, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('The Scientist', 2002, '00:05:09', 'thescientist.mp3', 'thescientist.png', 3400, 1700, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Clocks', 2003, '00:04:17', 'clocks.mp3', 'clocks.jpg', 3300, 1650, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Fix You', 2005, '00:04:54', 'fixyou.mp3', 'fixyou.jpg', 3100, 1550, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('Viva la Vida', 2008, '00:04:01', 'vivalavida.mp3', 'vivalavida.jpg', 3000, 1500, (SELECT genre_id FROM Genre WHERE genre_name = 'Electronic')),
('7 Rings', 2019, '00:03:42', '7rings.mp3', '7rings.png', 4300, 2150, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('God is a Woman', 2018, '00:03:17', 'godisawoman.mp3', 'godisawoman.png', 4200, 2100, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Break Up with Your Girlfriend, I m Bored', 2019, '00:03:20', 'breakupwithyourgirlfriend.mp3', 'breakupwithyourgirlfriend.png', 4100, 2050, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Thank U, Next', 2019, '00:03:28', 'thankunext.mp3', 'thankunext.png', 4000, 2000, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Into You', 2016, '00:04:03', 'intoyou.mp3', 'intoyou.png', 3900, 1950, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Side to Side', 2016, '00:03:52', 'sidetoside.mp3', 'sidetoside.png', 3800, 1900, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Dangerous Woman', 2016, '00:03:55', 'dangerouswoman.mp3', 'dangerouswoman.png', 3700, 1850, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Problem', 2014, '00:03:45', 'problem.mp3', 'problem.png', 3600, 1800, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Hotline Bling', 2015, '00:04:25', 'hotlinebling.mp3', 'hotlinebling.png', 4800, 2400, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('One Dance', 2016, '00:02:53', 'onedance.mp3', 'onedance.png', 4600, 2300, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('Controlla', 2016, '00:04:29', 'controlla.mp3', 'controlla.jpg', 4400, 2200, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('Started from the Bottom', 2013, '00:04:05', 'startedfromthebottom.mp3', 'startedfromthebottom.png', 4300, 2150, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('Hold On, We re Going Home', 2013, '00:04:18', 'holdonweregoinghome.mp3', 'holdonweregoinghome.jpg', 4200, 2100, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('Take Care', 2011, '00:04:40', 'takecare.mp3', 'takecare.jpg', 4100, 2050, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('Over', 2011, '00:04:24', 'over.mp3', 'over.jpg', 4000, 2000, (SELECT genre_id FROM Genre WHERE genre_name = 'Hip-hop')),
('Sorry', 2015, '00:03:22', 'sorry.mp3', 'sorry.png', 5300, 2650, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('What Do You Mean?', 2015, '00:03:39', 'whatdoyoumean.mp3', 'whatdoyoumean.png', 5200, 2600, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Where Are Ü Now', 2015, '00:04:08', 'whereareunow.mp3', 'whereareunow.jpg', 5100, 2550, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Boyfriend', 2012, '00:02:54', 'boyfriend.mp3', 'boyfriend.jpg', 5000, 2500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Baby', 2010, '00:03:34', 'baby.mp3', 'baby.jpg', 4900, 2450, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Never Say Never', 2010, '00:03:50', 'neversaynever.mp3', 'neversaynever.jpg', 4800, 2400, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('U Smile', 2010, '00:03:17', 'usmile.mp3', 'usmile.jpg', 4700, 2350, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),

('One Time', 2009, '00:03:08', 'onetime.mp3', 'onetime.jpg', 4600, 2300, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),

('The A Team', 2010, '00:04:18', 'theateam.mp3', 'TheATeam.jpg', 1000, 500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Yummy', 2017, '00:03:23', 'yummy.mp3', 'Yummy.png', 1500, 700, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Peaches', 2016, '00:03:18', 'peaches.mp3', 'Peaches.png', 2000, 1000, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Chasing Pavements', 2012, '00:03:30', 'chasingpavements.mp3', 'Chasing_Pavements.jpg', 2500, 1200, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Rolling In The Deep', 2011, '00:03:53', 'rollinginthedeep.mp3', 'Rolling_In_The_Deep.jpg', 3000, 1500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Bloodstream', 2014, '00:05:11', 'bloodstream.mp3', 'bloodstream.jpg', 3500, 1700, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('One Last Time', 2014, '00:03:18', 'onelasttime.mp3', 'One_Last_Time.png', 4000, 2000, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('The Way', 2013, '00:04:24', 'theway.mp3', 'The_Way.png', 4500, 2200, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('Shake It Off', 2015, '00:04:01', 'shakeitoff.mp3', 'Shake_It_Off.png', 5000, 2500, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop')),
('You Belong With Me', 2009, '00:03:48', 'youbelongwithme.mp3', 'youbelongwithme.jpg', 5500, 2700, (SELECT genre_id FROM Genre WHERE genre_name = 'Pop'));



-- Thêm dữ liệu vào bảng Artist_Song

INSERT INTO artist_song (artist_id, song_id) VALUES
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Style')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Bad Blood')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Wildest Dreams')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Out of the Woods')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Welcome to New York')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'I Knew You Were Trouble')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'We Are Never Ever Getting Back Together')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Red')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Thunder')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'It s Time')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Radioactive')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Demons')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'On Top of the World')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Shots')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Natural')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Walking the Wire')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Imagine Dragons'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Zero')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Don t Let Me Down')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Paris')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Roses')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Everybody Hates Me')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'The Chainsmokers'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Who Do You Love')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Thinking Out Loud')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Perfect')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Photograph')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Happier')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Galway Girl')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Castle on the Hill')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Dive')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Nancy Mulligan')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Eraser')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Someone Like You')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Set Fire to the Rain')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Rumour Has It')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Turning Tables')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'One and Only')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Lovesong')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Don t You Remember')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'I ll Be Waiting')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Memories')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Sugar')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Payphone')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Moves Like Jagger')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'This Love')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'She Will Be Loved')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Animals')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'One More Night')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Maroon 5'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Maps')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Hymn for the Weekend')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Adventure of a Lifetime')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'A Sky Full of Stars')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Paradise')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'The Scientist')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Clocks')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Yellow')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Fix You')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Coldplay'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Viva la Vida')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = '7 Rings')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'God is a Woman')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Break Up with Your Girlfriend, I m Bored')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Thank U, Next')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Into You')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Side to Side')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Dangerous Woman')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Problem')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Hotline Bling')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Passionfruit')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'One Dance')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Fake Love')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Controlla')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Started from the Bottom')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Hold On, We re Going Home')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Take Care')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Drake'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Over')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Sorry')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'What Do You Mean?')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Where Are Ü Now')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Boyfriend')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Baby')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Never Say Never')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'U Smile')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'One Time')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'You Belong With Me')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Taylor Swift'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Shake It Off')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Bloodstream')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ed Sheeran'), (SELECT song.song_id FROM Song WHERE song_tittle = 'The A Team')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Chasing Pavements')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Adele'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Rolling In The Deep')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'One Last Time')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Ariana Grande'), (SELECT song.song_id FROM Song WHERE song_tittle = 'The Way')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Yummy')),
                                                 ((SELECT artist_id FROM Artist WHERE artist_name = 'Justin Bieber'), (SELECT song.song_id FROM Song WHERE song_tittle = 'Peaches'));
