server:
  port: 8080

#  servlet:
#    context-path: /identity


spring:


  datasource:
    url: jdbc:mysql://localhost:3306/music_final
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    username: vuongthach03@gmail.com
    password: poikbvfphfhohcja
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

  application:
    name: sound_final
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

outbound:
  identity:
    client-id: "7147057967-181mac26t08vucjkmabjvtn7d40kjkt7.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
